// Generated 05 Nov 2021 10:18 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Carts
{
    [Serializable]
    public class CartsList
     : MEBusinessListBase<CartsList, Carts>
    {
        #region " Business Methods "

        public Carts GetItem(int CartID)
        {
            foreach (Carts child in this)
            {
                if (child.CartID == CartID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Carts";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }
            public int ? UserID { get; set; }

        }

        public static CartsList NewCartsList()
        {
            return new CartsList();
        }

        public CartsList()
        {
            // must have parameter-less constructor
        }

        public static CartsList GetCartsList()
        {
            return DataPortal.Fetch<CartsList>(new Criteria());
        }

        public static CartsList GetCartsList(int UserID)
        {
            return DataPortal.Fetch<CartsList>(new Criteria(){ UserID = UserID});
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(Carts.GetCarts(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getCartsList";
                        cm.Parameters.AddWithValue("@UserID", Singular.Security.Security.CurrentIdentity.UserID);
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}