// Generated 16 Nov 2021 10:52 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Carts
{
    [Serializable]
    public class ProductTransactionList
     : MEBusinessListBase<ProductTransactionList, ProductTransaction>
    {
        #region " Business Methods "

        public ProductTransaction GetItem(int TransactionID)
        {
            foreach (ProductTransaction child in this)
            {
                if (child.TransactionID == TransactionID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Product Transactions";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static ProductTransactionList NewProductTransactionList()
        {
            return new ProductTransactionList();
        }

        public ProductTransactionList()
        {
            // must have parameter-less constructor
        }

        public static ProductTransactionList GetProductTransactionList()
        {
            return DataPortal.Fetch<ProductTransactionList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(ProductTransaction.GetProductTransaction(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getProductTransactionList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}