// Generated 10 Nov 2021 11:06 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Maintenance
{
    [Serializable]
    public class ProductList
     : MEBusinessListBase<ProductList, Product>
    {
        #region " Business Methods "

        public Product GetItem(int ProductID)
        {
            foreach (Product child in this)
            {
                if (child.ProductID == ProductID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Products";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public int? ProductID;
            public int? ProductcategoryID = null;
            public Criteria()
            {
            }
            public Criteria(int? ProductcategoryID, int? ProductID)
            {
                this.ProductcategoryID = ProductcategoryID;
                this.ProductID = ProductID;
            }

        }

        public static ProductList NewProductList()
        {
            return new ProductList();
        }

        public ProductList()
        {
            // must have parameter-less constructor
        }

        public static ProductList GetProductList()
        {
            return DataPortal.Fetch<ProductList>(new Criteria());
        }
        public static ProductsList GetProductsList(int ProductCategoryID, int ProductID)
        {
            return DataPortal.Fetch<ProductsList>(new Criteria { ProductcategoryID = ProductCategoryID });
            return DataPortal.Fetch<ProductsList>(new Criteria { ProductID = ProductID });
        }
        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(Product.GetProduct(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getProductList";
                        cm.Parameters.AddWithValue("@ProductCategoriessID", Singular.Misc.ZeroDBNull(crit.ProductcategoryID));
                        cm.Parameters.AddWithValue("@ProductID", value: Singular.Misc.ZeroDBNull(crit.ProductID));
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}