// Generated 20 Oct 2021 12:01 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Maintenance
{
    [Serializable]
    public class ProductCategorieList
     : SingularBusinessListBase<ProductCategorieList, ProductCategorie>
    {
        #region " Business Methods "
        public ProductCategorie GetItem(int ProductCategoriessID)
        {
            foreach (ProductCategorie child in this)
            {
                if (child.ProductCategoriessID == ProductCategoriessID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Product Categories";
        }
        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
         : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static ProductCategorieList NewProductCategorieList()
        {
            return new ProductCategorieList();
        }


        public ProductCategorieList()
        {
            // must have parameter-less constructor
        }

        public static ProductCategorieList GetProductCategorieList()
        {
            return DataPortal.Fetch<ProductCategorieList>(new Criteria());
        }
      

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(ProductCategorie.GetProductCategorie(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getProductCategorieList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}