// Generated 22 Oct 2021 09:28 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.AccountTypes
{
    [Serializable]
    public class AccountTypesList
     : MEBusinessListBase<AccountTypesList, AccountTypes>
    {
        #region " Business Methods "

        public AccountTypes GetItem(int AccountTypeID)
        {
            foreach (AccountTypes child in this)
            {
                if (child.AccountTypeID == AccountTypeID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Account Types";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static AccountTypesList NewAccountTypesList()
        {
            return new AccountTypesList();
        }

        public AccountTypesList()
        {
            // must have parameter-less constructor
        }

        public static AccountTypesList GetAccountTypesList()
        {
            return DataPortal.Fetch<AccountTypesList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(AccountTypes.GetAccountTypes(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getAccountTypesList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}