// Generated 03 Nov 2021 09:37 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.RO
{
    [Serializable]
    public class ProductCategoriesList
     : MEBusinessListBase<ProductCategoriesList, ProductCategories>
    {
        #region " Business Methods "

        public ProductCategories GetItem(int ProductCategoriessID)
        {
            foreach (ProductCategories child in this)
            {
                if (child.ProductCategoriessID == ProductCategoriessID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Product Categories";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static ProductCategoriesList NewProductCategoriesList()
        {
            return new ProductCategoriesList();
        }

        public ProductCategoriesList()
        {
            // must have parameter-less constructor
        }

        public static ProductCategoriesList GetProductCategoriesList()
        {
            return DataPortal.Fetch<ProductCategoriesList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(ProductCategories.GetProductCategories(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getProductCategoriesList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}