// Generated 04 Nov 2021 13:58 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Products
{
    [Serializable]
    public class ProductsList
     : MEBusinessListBase<ProductsList, Products>
    {
        #region " Business Methods "

        public Products GetItem(int ProductID)
        {
            foreach (Products child in this)
            {
                if (child.ProductID == ProductID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Products";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public int? ProductID;
            public int? ProductcategoryID = null;
            public Criteria()
            {
            }
            public Criteria(int? ProductcategoryID,int? ProductID)
            {
                this.ProductcategoryID = ProductcategoryID;
                this.ProductID = ProductID;
             
             
            }
        }

        public static ProductsList NewProductsList()
        {
            return new ProductsList();
        }

        public ProductsList()
        {
            // must have parameter-less constructor
        }

        public static ProductsList GetProductsList()
        {
            return DataPortal.Fetch<ProductsList>(new Criteria());
        }

        public static ProductsList GetProductsList( int ProductCategoryID, int ProductID)
        {
            return DataPortal.Fetch<ProductsList>(new Criteria { ProductcategoryID = ProductCategoryID, ProductID = ProductID });
            
     
        }

        public static ProductsList GetProducts()
        {
            return DataPortal.Fetch<ProductsList>(new Criteria() );
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(Products.GetProducts(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getProductsList";
                        cm.Parameters.AddWithValue("@ProductCategoriessID", Singular.Misc.ZeroDBNull(crit.ProductcategoryID));
                        cm.Parameters.AddWithValue("@ProductID", Singular.Misc.ZeroDBNull(crit.ProductID));
                       

                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}